development: &development
  :url: redis://localhost:6379
  :host: localhost
  :port: 6379
  :timeout: 1
  :inline: true
test: *development
production: &production
  :url: redis://localhost:6379
  :host: {redis_host}
  :port: {redis_port}
  :inline: true
  :timeout: 1